apiVersion: v1
kind: Pod
metadata:
  name: pod-configmap-env
spec:
  restartPolicy: Never
  containers:
    - name: ct-debian
      image: debian
      command: [ "/bin/sh", "-c", "env && sleep 3000" ]
      env:
        - name: SPECIAL_LEVEL_KEY
          valueFrom:
            configMapKeyRef:
              name: config1
              key: special.how
        - name: SPECIAL_TYPE_KEY
          valueFrom:
            configMapKeyRef:
              name: config1
              key: special.type
