apiVersion: v1
kind: Pod
metadata:
  name: pod-vol-emptydir
spec:
  restartPolicy: Never
  volumes:
  - name: data
    emptyDir: {}

  containers:
  - name: ct-debian
    image: debian
    volumeMounts:
    - name: data
      mountPath: /data
    command: ['/bin/sh', '-c', 'sleep 3000']